repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.62.3 # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
  hooks:
    - id: terraform_fmt
    - id: terraform_validate
    - id: terraform_tflint
      args:
        - --args=--enable-rule=terraform_comment_syntax
        - --args=--enable-rule=terraform_deprecated_interpolation
        - --args=--enable-rule=terraform_documented_outputs
        - --args=--enable-rule=terraform_documented_variables
        - --args=--enable-rule=terraform_naming_convention
        - --args=--enable-rule=terraform_required_providers
        - --args=--enable-rule=terraform_standard_module_structure
        - --args=--enable-rule=terraform_typed_variables
        - --args=--enable-rule=terraform_unused_declarations
        - --args=--enable-rule=terraform_unused_required_providers
        - --args=--enable-rule=terraform_workspace_remote
        - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl
    - id: terraform_tfsec
      args:
        - --args=--tfvars-file=terraform.tfvars
    - id: terraform_docs
      args:
        - --hook-config=--path-to-file=README.md        # Valid UNIX path. I.e. ../TFDOC.md or docs/README.md etc.
        - --hook-config=--add-to-existing-file=true     # Boolean. true or false
        - --hook-config=--create-file-if-not-exist=true # Boolean. true or false
    # - id: infracost_breakdown
    #   args:
    #     - --args=--path .
    #   verbose: true # Always show costs
